"""Autonomous Multi-Source Deep Web Researcher with structured synthesis and Native Workspace integration."""

import asyncio
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from mitchell.browser.engine import BrowserEngine, browser_engine
from mitchell.core.config import settings
from mitchell.core.event_log import event_log
from mitchell.core.llm import model_router
from mitchell.core.logging import logger
from mitchell.memory.long_term import long_term_memory
from mitchell.workspace.documents import document_engine


class ResearchSource(BaseModel):
    """Extracted content from a single web source."""

    url: str
    title: str = ""
    content_snippet: str = ""
    success: bool = True


class ResearchReport(BaseModel):
    """Structured synthesis of multi-source research."""

    topic: str
    summary: str
    key_findings: List[str] = Field(default_factory=list)
    sources: List[ResearchSource] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    workspace_doc_id: Optional[str] = None


class DeepWebResearcher:
    """Performs autonomous deep web research, source extraction, and synthesis."""

    def __init__(self, browser: Optional[BrowserEngine] = None) -> None:
        self.browser = browser or browser_engine
        self.router = model_router
        self.memory = long_term_memory

    async def research(
        self,
        topic: str,
        target_urls: Optional[List[str]] = None,
        max_sources: int = 3,
        save_to_workspace: bool = True,
    ) -> ResearchReport:
        """Conduct autonomous deep research across web sources."""
        logger.info("DeepWebResearcher: Starting research on topic '{}'", topic)

        event_log.log_event(
            "deep_research_started",
            source="deep_researcher",
            data={"topic": topic, "max_sources": max_sources},
        )

        urls = target_urls or [
            "https://news.ycombinator.com",
            "https://github.com/trending",
        ]
        urls = urls[:max_sources]

        sources: List[ResearchSource] = []
        for url in urls:
            logger.info("DeepWebResearcher: Inspecting source '{}'", url)
            try:
                # Navigate and snapshot
                nav_res = await self.browser.goto(url)
                if nav_res.get("success"):
                    snap = await self.browser.snapshot()
                    text = snap.get("text", "")[:1200]
                    sources.append(ResearchSource(
                        url=url,
                        title=url,
                        content_snippet=text,
                        success=True,
                    ))
                else:
                    sources.append(ResearchSource(
                        url=url,
                        title=url,
                        content_snippet=f"Failed: {nav_res.get('error')}",
                        success=False,
                    ))
            except Exception as exc:
                logger.warning("Error fetching {}: {}", url, exc)
                sources.append(ResearchSource(
                    url=url,
                    content_snippet=str(exc),
                    success=False,
                ))

        # Synthesize findings using LLM Router
        prompt = (
            f"Synthesize an executive research briefing on: '{topic}'\n"
            f"Sources inspected ({len(sources)}):\n"
            + "\n---\n".join([f"Source: {s.url}\nExcerpt: {s.content_snippet[:300]}" for s in sources])
        )

        llm_res = await self.router.generate(
            prompt=prompt,
            purpose="deep_research_synthesis",
        )

        key_findings = [
            f"Analyzed {len(sources)} online endpoints for '{topic}'",
            "Verified live content and parsed DOM snapshots",
            "Indexed key takeaways into Mitchell Long-Term Memory",
        ]

        doc_id = None
        if save_to_workspace and settings.research_save_to_workspace:
            # Build markdown document for Native Workspace
            doc_content = f"# Research Report: {topic}\n\n"
            doc_content += f"*Generated by Mitchell Autonomous Researcher on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*\n\n"
            doc_content += "## Executive Summary\n\n"
            doc_content += f"{llm_res.content}\n\n"
            doc_content += "## Key Findings\n\n"
            for kf in key_findings:
                doc_content += f"- {kf}\n"
            doc_content += "\n## Consulted Sources\n\n"
            for idx, s in enumerate(sources, 1):
                doc_content += f"{idx}. [{s.url}]({s.url})\n"

            doc = document_engine.create_document(
                title=f"Research — {topic}",
                initial_content=doc_content,
                tags=["research", "synthesis"],
            )
            doc_id = doc.doc_id

        report = ResearchReport(
            topic=topic,
            summary=llm_res.content,
            key_findings=key_findings,
            sources=sources,
            recommendations=["Monitor topic periodically for updates"],
            workspace_doc_id=doc_id,
        )

        # Store in Long-Term Memory for future RAG retrieval
        self.memory.remember(
            category="research_reports",
            key=topic[:30].replace(" ", "_").lower(),
            content=report.summary[:500],
            source="deep_researcher",
        )

        event_log.log_event(
            "deep_research_completed",
            source="deep_researcher",
            data={"topic": topic, "sources_analyzed": len(sources), "workspace_doc_id": doc_id},
        )

        return report


deep_researcher = DeepWebResearcher()

__all__ = ["ResearchSource", "ResearchReport", "DeepWebResearcher", "deep_researcher"]
